---

- name: Create etcd group
  ansible.builtin.group:
    name: etcd
    state: present

- name: Create etcd user
  ansible.builtin.user:
    name: etcd
    shell: /bin/nologin
    group: etcd
    comment: etcd user
    state: present

- name: Check if separate partition
  ansible.builtin.command: grep '/usr/local ' /proc/mounts
  changed_when: false
  register: partition_result
  failed_when: partition_result.rc >= 2

- name: Copy systemctl config file for kernel hardening
  ansible.builtin.copy:
# Begin Patch Evantage
# Removed:
    # src: "{{ '/usr/local/share/rke2/rke2-cis-sysctl.conf' if (usr_local.stat.writeable) and (partition_result.rc == 1) else '/opt/rke2/share/rke2/rke2-cis-sysctl.conf' }}"
# Added:
    src: "{{ rke2_share_path }}/rke2-cis-sysctl.conf"
# End Patch Evantage
    dest: /etc/sysctl.d/60-rke2-cis.conf
    mode: 0600
    remote_src: true
  notify: Restart systemd-sysctl

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
